-- CreateTable
CREATE TABLE "MPU6050" (
    "id" TEXT NOT NULL,
    "accX" DOUBLE PRECISION NOT NULL,
    "accY" DOUBLE PRECISION NOT NULL,
    "accZ" DOUBLE PRECISION NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MPU6050_pkey" PRIMARY KEY ("id")
);
